# Generated by Django 4.2.13 on 2024-05-27 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='phone number')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(blank=True, null=True, verbose_name='date joined')),
                ('date_left', models.DateTimeField(blank=True, null=True, verbose_name='date left')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('editor_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notes_editor', to=settings.AUTH_USER_MODEL)),
                ('user_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notes_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=255, verbose_name='image name')),
                ('image', models.ImageField(upload_to='user_images/', verbose_name='image')),
                ('user_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeInformations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_number', models.CharField(max_length=3, validators=[user.models.EmployeeInformations.only_int], verbose_name='institution number')),
                ('transit_number', models.CharField(max_length=5, validators=[user.models.EmployeeInformations.only_int], verbose_name='transit number')),
                ('account_number', models.CharField(max_length=7, validators=[user.models.EmployeeInformations.only_int], verbose_name='account number')),
                ('sin_number', models.CharField(max_length=9, validators=[user.models.EmployeeInformations.only_int], verbose_name='sin number')),
                ('wage', models.FloatField(verbose_name='wage')),
                ('wage_is_based_on', models.IntegerField(choices=[(0, 'hour'), (1, 'month'), (2, 'year')])),
                ('employee_type_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.employeetypes')),
                ('user_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255, verbose_name='field')),
                ('before', models.CharField(max_length=255, verbose_name='before')),
                ('after', models.CharField(max_length=255, verbose_name='after')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='timestamp')),
                ('editor_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_changelogs_editor', to=settings.AUTH_USER_MODEL)),
                ('user_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_changelogs_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(help_text='Street address or P.O. Box', max_length=255, verbose_name='adress1')),
                ('address2', models.CharField(blank=True, help_text='(Optional) Apt, Suite, Unit, Building', max_length=255, null=True, verbose_name='adress2')),
                ('city', models.CharField(max_length=255, verbose_name='city')),
                ('postal_code', models.CharField(max_length=255, verbose_name='postal code')),
                ('province', models.CharField(max_length=255, verbose_name='province')),
                ('user_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
