# Generated by Django 4.2.13 on 2024-05-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinformations',
            name='wage',
            field=models.FloatField(blank=True, null=True, verbose_name='wage'),
        ),
        migrations.AlterField(
            model_name='employeeinformations',
            name='wage_is_based_on',
            field=models.IntegerField(blank=True, choices=[(0, 'hour'), (1, 'month'), (2, 'year')], null=True),
        ),
    ]
